dist: trusty
sudo: required

language: python
python:
  - "3.5"

env:
  - SKIP_NETWORK_TESTS=0

install:
    - travis_retry pip install tox
    # XXX Avoid snapcraft from loading useless libs when running on Ubuntu
    - sudo truncate -s 0 /etc/os-release
script:
    - tox -e py35
after_success:
    - tox -e py35-coveralls
